/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uv.fei.sistemaproyectostitulacion.gui;


/**
 *
 * @author Zinedinne
 */
public class RegistroEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form RegistroEmpleados
     */
    
    
   
    
    public RegistroEmpleados() {
        initComponents();
      
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcademicos = new javax.swing.JButton();
        btnSecretariado = new javax.swing.JButton();
        btnServicioSocial = new javax.swing.JButton();
        panelMostrar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcademicos.setText("Académicos");
        btnAcademicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcademicosMouseClicked(evt);
            }
        });
        getContentPane().add(btnAcademicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnSecretariado.setText("Secretariado");
        btnSecretariado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSecretariadoMouseClicked(evt);
            }
        });
        getContentPane().add(btnSecretariado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        btnServicioSocial.setText("Servicio Social");
        btnServicioSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServicioSocialMouseClicked(evt);
            }
        });
        getContentPane().add(btnServicioSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        javax.swing.GroupLayout panelMostrarLayout = new javax.swing.GroupLayout(panelMostrar);
        panelMostrar.setLayout(panelMostrarLayout);
        panelMostrarLayout.setHorizontalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        panelMostrarLayout.setVerticalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        getContentPane().add(panelMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcademicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcademicosMouseClicked
        panelAcademico registroAcademico = new panelAcademico();
        registroAcademico.setSize(413, 315);
        registroAcademico.setLocation(0,0);
        
        panelMostrar.removeAll();
        panelMostrar.add(registroAcademico);
        panelMostrar.revalidate();
        panelMostrar.repaint();
    }//GEN-LAST:event_btnAcademicosMouseClicked

    private void btnSecretariadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecretariadoMouseClicked
        panelSecretariado registroSecretariado = new panelSecretariado();
        registroSecretariado.setSize(413, 315);
        registroSecretariado.setLocation(0,0);
        
        panelMostrar.removeAll();
        panelMostrar.add(registroSecretariado);
        panelMostrar.revalidate();
        panelMostrar.repaint();
    }//GEN-LAST:event_btnSecretariadoMouseClicked

    private void btnServicioSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicioSocialMouseClicked
        panelServicioSocial registroServicioSocial = new panelServicioSocial();
        registroServicioSocial.setSize(413, 315);
        registroServicioSocial.setLocation(0,0);
        
        panelMostrar.removeAll();
        panelMostrar.add(registroServicioSocial);
        panelMostrar.revalidate();
        panelMostrar.repaint();
    }//GEN-LAST:event_btnServicioSocialMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUIMenu menu = new GUIMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcademicos;
    private javax.swing.JButton btnSecretariado;
    private javax.swing.JButton btnServicioSocial;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelMostrar;
    // End of variables declaration//GEN-END:variables
}
